[package]
name = "net"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]

tokio-util = "0.7.12"

# tsify next dependencies
wasm-bindgen = "0.2.89"
tsify-next = "0.5.4"
serde = { version = "1.0", features = ["derive"] }
